CREATE SEQUENCE COTM_CR_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 CYCLE NOCACHE;

GRANT SELECT ON COTM_CR_SEQ TO TBAGEN,TBACUST,TBAUTIL,TBAADM;
CREATE PUBLIC SYNONYM COTM_CR_SEQ FOR COTM_CR_SEQ;